// One-shot generator — run once to emit businesses.js
import { writeFileSync } from "fs";

const categories = [
  "Food & Beverage", "Health & Wellness", "Technology", "Professional Services",
  "Retail", "Creative Studio", "Home Services", "Education", "Travel & Hospitality",
  "Finance", "Real Estate", "Automotive", "Beauty & Spa", "Fitness", "Legal",
  "Nonprofit", "Entertainment", "Construction", "Agriculture", "Logistics"
];

const layouts = [
  "hero-split", "hero-centered", "hero-asymmetric", "hero-minimal",
  "hero-grid", "hero-magazine", "hero-bold", "hero-soft",
  "hero-stack", "hero-cinema"
];

const scenes = ["orbs", "particles", "waves", "geometry", "rings", "lattice"];

const palettes = [
  { name: "Ink Teal", bg: "#0b0f0e", surface: "#141a18", fg: "#e8eeec", muted: "#8a9a94", accent: "#2dd4a8", accent2: "#0d9488", dark: true },
  { name: "Slate Copper", bg: "#0f0e0c", surface: "#1a1814", fg: "#f2ebe3", muted: "#9a9084", accent: "#d4896a", accent2: "#a65d42", dark: true },
  { name: "Midnight Navy", bg: "#0a0c12", surface: "#12161f", fg: "#e6eaf2", muted: "#8b93a7", accent: "#6b9eff", accent2: "#3b6fd4", dark: true },
  { name: "Forest Ember", bg: "#0c100c", surface: "#151b15", fg: "#e9efe8", muted: "#8c988a", accent: "#e07a3d", accent2: "#2f6b4f", dark: true },
  { name: "Charcoal Rose", bg: "#100d0f", surface: "#1b1518", fg: "#f3e8ec", muted: "#a08a92", accent: "#e8a0b0", accent2: "#b85c72", dark: true },
  { name: "Deep Graphite", bg: "#0c0c0e", surface: "#161618", fg: "#ececed", muted: "#8e8e96", accent: "#a8b0c0", accent2: "#6a7280", dark: true },
  { name: "Ocean Ink", bg: "#070d12", surface: "#0f1820", fg: "#e4eef6", muted: "#7d92a6", accent: "#38bdf8", accent2: "#0284c7", dark: true },
  { name: "Warm Stone", bg: "#f6f1ea", surface: "#ffffff", fg: "#1c1916", muted: "#6b635a", accent: "#b45309", accent2: "#78350f", dark: false },
  { name: "Paper Sage", bg: "#f3f5f1", surface: "#ffffff", fg: "#1a1f1a", muted: "#5f6b5f", accent: "#3f6f5a", accent2: "#2a4d3e", dark: false },
  { name: "Cloud Blue", bg: "#f0f4f8", surface: "#ffffff", fg: "#0f1720", muted: "#5a6a7a", accent: "#2563eb", accent2: "#1e3a8a", dark: false },
  { name: "Cream Citrus", bg: "#faf6ef", surface: "#ffffff", fg: "#1a1712", muted: "#6e6658", accent: "#ca8a04", accent2: "#854d0e", dark: false },
  { name: "Blush Clay", bg: "#faf3f0", surface: "#ffffff", fg: "#1f1614", muted: "#7a6560", accent: "#c2410c", accent2: "#7c2d12", dark: false },
  { name: "Mint Clean", bg: "#f0faf6", surface: "#ffffff", fg: "#0f1f1a", muted: "#56706a", accent: "#0d9488", accent2: "#115e59", dark: false },
  { name: "Lavender Mist", bg: "#f5f3f9", surface: "#ffffff", fg: "#17141f", muted: "#6b6478", accent: "#6d5a8d", accent2: "#3f3558", dark: false },
  { name: "Noir Gold", bg: "#0a0908", surface: "#161411", fg: "#f5f0e6", muted: "#9a9080", accent: "#c9a227", accent2: "#8a6f14", dark: true },
  { name: "Arctic", bg: "#eef2f5", surface: "#ffffff", fg: "#0c1218", muted: "#5c6b78", accent: "#0e7490", accent2: "#164e63", dark: false },
  { name: "Plum Night", bg: "#0e0a10", surface: "#18121c", fg: "#f0e8f4", muted: "#95889e", accent: "#c084fc", accent2: "#7e22ce", dark: true },
  { name: "Olive Studio", bg: "#12140f", surface: "#1c1f17", fg: "#eef0e6", muted: "#929884", accent: "#a3b18a", accent2: "#588157", dark: true },
  { name: "Coral Sand", bg: "#faf5f2", surface: "#ffffff", fg: "#1c1412", muted: "#7a6660", accent: "#e07a5f", accent2: "#9b4d3a", dark: false },
  { name: "Steel Cyan", bg: "#0a0e11", surface: "#12181d", fg: "#e6eef2", muted: "#7f919c", accent: "#22d3ee", accent2: "#0e7490", dark: true },
];

const businesses = [
  // Food & Beverage (1-10)
  { name: "Hearth & Grain", tagline: "Sourdough, fire, and the long table", category: "Food & Beverage", type: "Artisan Bakery", desc: "Neighborhood bakery crafting daily sourdough, laminated pastries, and seasonal loaves from heritage grains.", features: ["Same-day sourdough", "Subscription boxes", "Private bake classes", "Local grain partners"], cta: "Order fresh bread", stats: [{n:"12k",l:"Loaves / mo"},{n:"40+",l:"Grain partners"},{n:"4.9",l:"Local rating"}] },
  { name: "Lumen Roast", tagline: "Coffee roasted for the curious", category: "Food & Beverage", type: "Specialty Coffee", desc: "Micro-roastery sourcing single-origin lots and serving precision espresso in a calm, light-filled space.", features: ["Single-origin focus", "Cupping labs", "Wholesale program", "Brew gear bar"], cta: "Find your roast", stats: [{n:"28",l:"Origins"},{n:"3",l:"Cafés"},{n:"98%",l:"Direct trade"}] },
  { name: "Maré Kitchen", tagline: "Coastal plates, seasonal catch", category: "Food & Beverage", type: "Seafood Restaurant", desc: "Fine-casual seafood restaurant celebrating coastal harvest with a chef’s counter and natural wine list.", features: ["Daily catch board", "Chef’s counter", "Natural wines", "Private dining"], cta: "Reserve a table", stats: [{n:"18",l:"Seats at bar"},{n:"2hr",l:"From boat to plate"},{n:"★★★★",l:"Guide listed"}] },
  { name: "Verde Bowl", tagline: "Fast bowls that still feel real", category: "Food & Beverage", type: "Healthy Fast Casual", desc: "Build-your-own grain bowls and cold-pressed juices for people who won’t compromise on ingredients.", features: ["Custom bowls", "Meal prep kits", "Corporate catering", "Zero plastic"], cta: "Build a bowl", stats: [{n:"6",l:"Locations"},{n:"45s",l:"Avg order"},{n:"100%",l:"Compostable"}] },
  { name: "Nocturne Bar", tagline: "Cocktails after dark", category: "Food & Beverage", type: "Cocktail Bar", desc: "Intimate cocktail lounge with house-aged spirits, live jazz nights, and a seasonal tasting menu.", features: ["House-aged spirits", "Live jazz", "Tasting flights", "Members lounge"], cta: "Book a seat", stats: [{n:"48",l:"Signature drinks"},{n:"Fri",l:"Jazz nights"},{n:"22:00",l:"Doors open"}] },
  { name: "Pasta Forme", tagline: "Handmade pasta, nothing else", category: "Food & Beverage", type: "Italian Restaurant", desc: "Open-kitchen pasta house rolling dough in plain sight—regional shapes, slow sauces, family tables.", features: ["Fresh pasta daily", "Regional recipes", "Wine cellar", "Kids welcome"], cta: "See tonight’s menu", stats: [{n:"16",l:"Shapes"},{n:"3hr",l:"Sauce simmer"},{n:"120",l:"Seats"}] },
  { name: "Sweet Circuit", tagline: "Pastry engineered for joy", category: "Food & Beverage", type: "Patisserie", desc: "Modern patisserie blending classic French technique with playful flavors and geometric presentation.", features: ["Weekend specials", "Wedding cakes", "Tea service", "Online preorder"], cta: "Browse desserts", stats: [{n:"30+",l:"Creations"},{n:"48h",l:"Preorder"},{n:"★ 4.8",l:"Reviews"}] },
  { name: "Smoke & Cedar", tagline: "Low and slow, done right", category: "Food & Beverage", type: "BBQ Smokehouse", desc: "Texas-style pit BBQ with house rubs, craft beer, and picnic tables under the cedars.", features: ["All-day pit", "Craft beer", "Catering trucks", "Family packs"], cta: "Check the line", stats: [{n:"14hr",l:"Brisket cook"},{n:"8",l:"On tap"},{n:"Est. 2014",l:"Since"}] },
  { name: "Fresco Market", tagline: "Farm stand energy, every day", category: "Food & Beverage", type: "Grocery Market", desc: "Curated grocer for produce, pantry staples, and prepared foods from regional farms.", features: ["Daily produce", "Hot bar", "Farm partners", "Delivery slots"], cta: "Shop the market", stats: [{n:"80+",l:"Farms"},{n:"Same day",l:"Delivery"},{n:"Organic",l:"First"}] },
  { name: "Tiffin Lab", tagline: "South Asian flavors, modern pace", category: "Food & Beverage", type: "Indian Kitchen", desc: "Counter-service Indian kitchen with rotating regional thalis and spice-forward small plates.", features: ["Regional thalis", "Spice flights", "Vegan menu", "Lunch rush ready"], cta: "Order tiffin", stats: [{n:"5",l:"Regions"},{n:"15m",l:"Pickup"},{n:"Gluten-free",l:"Options"}] },

  // Health (11-15)
  { name: "Aether Clinic", tagline: "Primary care that listens", category: "Health & Wellness", type: "Medical Clinic", desc: "Modern primary care practice with longer visits, same-day telehealth, and coordinated specialists.", features: ["30-min visits", "Telehealth", "Lab on site", "Care coordination"], cta: "Book a visit", stats: [{n:"Same day",l:"Openings"},{n:"4.9",l:"Patient score"},{n:"12",l:"Providers"}] },
  { name: "Stillwater Dental", tagline: "Calm dentistry for real life", category: "Health & Wellness", type: "Dental Practice", desc: "Anxiety-aware dental studio with digital imaging, clear pricing, and evening appointments.", features: ["Digital scans", "Sedation options", "Transparent fees", "Eve hours"], cta: "Schedule exam", stats: [{n:"0%",l:"Surprise bills"},{n:"Evening",l:"Slots"},{n:"15yr",l:"Avg tenure"}] },
  { name: "Pulse Physio", tagline: "Move without fear again", category: "Health & Wellness", type: "Physical Therapy", desc: "Sports and orthopedic physio with one-on-one sessions and return-to-play programs.", features: ["1:1 sessions", "Sports rehab", "Home programs", "Post-op care"], cta: "Start recovery", stats: [{n:"45min",l:"Sessions"},{n:"92%",l:"Return to sport"},{n:"Board",l:"Certified"}] },
  { name: "Nova Mind", tagline: "Therapy that fits your week", category: "Health & Wellness", type: "Mental Health", desc: "Licensed therapists offering in-person and virtual sessions with transparent matching.", features: ["Therapist match", "Virtual & in-person", "Sliding scale", "Group workshops"], cta: "Find a therapist", stats: [{n:"40+",l:"Clinicians"},{n:"48h",l:"First match"},{n:"HIPAA",l:"Secure"}] },
  { name: "Root & Bloom", tagline: "Herbal care, clinical rigor", category: "Health & Wellness", type: "Integrative Wellness", desc: "Integrative wellness studio combining herbalism, nutrition coaching, and labs.", features: ["Herbal consults", "Nutrition plans", "Lab panels", "Workshops"], cta: "Explore care", stats: [{n:"ND",l:"On staff"},{n:"200+",l:"Formulas"},{n:"Evidence",l:"Based"}] },

  // Technology (16-25)
  { name: "Signal Stack", tagline: "Observability without the noise", category: "Technology", type: "SaaS / DevTools", desc: "Unified logs, metrics, and traces for teams who want signal—not another dashboard to babysit.", features: ["Unified telemetry", "Smart alerts", "Open standards", "SOC2 ready"], cta: "Start free trial", stats: [{n:"10B",l:"Events / day"},{n:"99.99%",l:"Uptime"},{n:"<5min",l:"Setup"}] },
  { name: "Canvas AI", tagline: "Design systems that write themselves", category: "Technology", type: "AI Product", desc: "AI design copilot that turns product specs into production-ready UI components and tokens.", features: ["Spec to UI", "Token sync", "Figma export", "Team libraries"], cta: "Generate a screen", stats: [{n:"3x",l:"Faster handoff"},{n:"50+",l:"Frameworks"},{n:"Enterprise",l:"SSO"}] },
  { name: "Parcel Grid", tagline: "Logistics APIs that just ship", category: "Technology", type: "Logistics Tech", desc: "Developer-first shipping APIs with real-time rates, labels, and tracking across carriers.", features: ["Multi-carrier", "Rate shopping", "Webhooks", "Sandbox first"], cta: "Get API keys", stats: [{n:"40+",l:"Carriers"},{n:"120ms",l:"Rate p50"},{n:"Global",l:"Coverage"}] },
  { name: "Keystone ID", tagline: "Auth that disappears", category: "Technology", type: "Identity Platform", desc: "Passwordless identity platform for consumer apps—passkeys, magic links, and fraud signals.", features: ["Passkeys", "Fraud signals", "SDKs", "Compliance kits"], cta: "Secure your app", stats: [{n:"99.95%",l:"Auth uptime"},{n:"12",l:"SDKs"},{n:"GDPR",l:"Ready"}] },
  { name: "Northline CRM", tagline: "CRM for operators, not admins", category: "Technology", type: "B2B SaaS", desc: "Lightweight CRM built for sales teams who hate data entry and love pipeline clarity.", features: ["Auto capture", "Pipeline views", "Email sync", "Mobile first"], cta: "See the demo", stats: [{n:"2min",l:"Daily admin"},{n:"+28%",l:"Win rate"},{n:"Free",l:"Up to 3 seats"}] },
  { name: "Lattice Cloud", tagline: "Infrastructure you can reason about", category: "Technology", type: "Cloud Platform", desc: "Composable cloud for teams who want Kubernetes power without the ops theater.", features: ["One-click clusters", "GitOps native", "Cost maps", "24/7 support"], cta: "Deploy now", stats: [{n:"50%",l:"Lower ops load"},{n:"Global",l:"Regions"},{n:"ISO",l:"Certified"}] },
  { name: "Echo Docs", tagline: "Docs that stay true to the code", category: "Technology", type: "Documentation", desc: "Living documentation platform that syncs API references, changelogs, and guides from your repo.", features: ["Repo sync", "API explorer", "Versioned", "Search that works"], cta: "Import a repo", stats: [{n:"Zero",l:"Stale pages"},{n:"OpenAPI",l:"Native"},{n:"SSO",l:"Included"}] },
  { name: "Flux Analytics", tagline: "Product analytics without the maze", category: "Technology", type: "Analytics", desc: "Event analytics for product teams—funnels, retention, and session replay in one calm UI.", features: ["Funnels", "Retention", "Replay", "SQL access"], cta: "Instrument free", stats: [{n:"<1 day",l:"To insight"},{n:"EU",l:"Hosting"},{n:"No",l:"Sampling tax"}] },
  { name: "Harbor Pay", tagline: "Payments for platforms", category: "Technology", type: "Fintech API", desc: "Embedded payments and payouts for marketplaces—onboarding, splits, and compliance included.", features: ["Marketplace splits", "KYC flows", "Global payouts", "Dispute tools"], cta: "Talk to sales", stats: [{n:"40+",l:"Countries"},{n:"PCI",l:"Level 1"},{n:"2 days",l:"Go-live"}] },
  { name: "Orbit Support", tagline: "Customer support that scales calmly", category: "Technology", type: "Helpdesk SaaS", desc: "Omnichannel helpdesk with AI drafts, knowledge base, and SLAs your team can actually hit.", features: ["Omnichannel", "AI drafts", "KB", "SLA dashboards"], cta: "Try Orbit", stats: [{n:"35%",l:"Faster replies"},{n:"Unlimited",l:"Agents plan"},{n:"SOC2",l:"Type II"}] },

  // Professional (26-32)
  { name: "Meridian Advisory", tagline: "Strategy with teeth", category: "Professional Services", type: "Consulting", desc: "Boutique strategy firm for mid-market companies navigating growth, M&A, and operating models.", features: ["Growth strategy", "M&A diligence", "Ops redesign", "Board briefings"], cta: "Request a briefing", stats: [{n:"120+",l:"Engagements"},{n:"18yr",l:"Avg partner exp"},{n:"Global",l:"Clients"}] },
  { name: "Ledger & Co", tagline: "Accounting that scales with you", category: "Professional Services", type: "Accounting Firm", desc: "Cloud-native accounting firm for startups and SMBs—books, tax, and CFO-as-a-service.", features: ["Monthly close", "Tax planning", "Fractional CFO", "Startup packages"], cta: "Get a quote", stats: [{n:"500+",l:"Clients"},{n:"48h",l:"Response"},{n:"CPA",l:"Led"}] },
  { name: "Brightline HR", tagline: "People ops without the paperwork fog", category: "Professional Services", type: "HR Consulting", desc: "HR partner for growing teams—handbooks, hiring systems, and culture that survives scale.", features: ["Handbook design", "Hiring systems", "Manager training", "Compliance audits"], cta: "Book a consult", stats: [{n:"80+",l:"Companies"},{n:"14 day",l:"Kickoff"},{n:"Remote",l:"Friendly"}] },
  { name: "Pivot PR", tagline: "Stories that land coverage", category: "Professional Services", type: "PR Agency", desc: "Public relations studio for tech and consumer brands who need narrative, not noise.", features: ["Media strategy", "Launch campaigns", "Executive profiles", "Crisis support"], cta: "Pitch us", stats: [{n:"200+",l:"Placements / yr"},{n:"Tier-1",l:"Outlets"},{n:"Retainer",l:"Flexible"}] },
  { name: "Scaffold Studio", tagline: "Architecture for places people love", category: "Professional Services", type: "Architecture", desc: "Architecture practice focused on adaptive reuse, sustainable materials, and human-scale spaces.", features: ["Adaptive reuse", "Sustainable design", "3D visualization", "Permit support"], cta: "Start a project", stats: [{n:"60+",l:"Built projects"},{n:"LEED",l:"Accredited"},{n:"Civic",l:"+ Private"}] },
  { name: "Northwind Research", tagline: "Insights that change decisions", category: "Professional Services", type: "Market Research", desc: "Qual and quant research for product and brand teams who need truth before roadmap bets.", features: ["User interviews", "Survey design", "Persona maps", "War rooms"], cta: "Plan a study", stats: [{n:"1k+",l:"Studies"},{n:"Global",l:"Panels"},{n:"2 wk",l:"Sprint option"}] },
  { name: "Apex Security", tagline: "Security reviews that ship blockers, not binders", category: "Professional Services", type: "Cybersecurity", desc: "Penetration testing and security architecture for product companies shipping fast.", features: ["Pen tests", "Architecture review", "Incident response", "Training"], cta: "Schedule assess", stats: [{n:"0",l:"Fluff reports"},{n:"48h",l:"Critical path"},{n:"CREST",l:"Team"}] },

  // Retail (33-40)
  { name: "Thread & Form", tagline: "Everyday clothes, exceptional cut", category: "Retail", type: "Apparel Brand", desc: "Direct-to-consumer apparel with responsible fabrics and a fit that lasts seasons, not weeks.", features: ["Responsible fabrics", "Fit guarantee", "Repairs", "Seasonal drops"], cta: "Shop the line", stats: [{n:"Carbon",l:"Neutral ship"},{n:"Free",l:"Repairs yr 1"},{n:"4.8",l:"Fit score"}] },
  { name: "Object House", tagline: "Objects with intent", category: "Retail", type: "Home Goods", desc: "Curated home goods shop for ceramics, lighting, and textiles from independent makers.", features: ["Maker stories", "Gift registry", "In-store events", "Worldwide ship"], cta: "Browse objects", stats: [{n:"120+",l:"Makers"},{n:"Weekly",l:"New finds"},{n:"Gift",l:"Wrap free"}] },
  { name: "Trailform Gear", tagline: "Pack light. Go far.", category: "Retail", type: "Outdoor Gear", desc: "Ultralight outdoor gear tested on real trails—packs, shells, and camp systems.", features: ["Field tested", "Lifetime program", "Pack fitting", "Trail guides"], cta: "Gear up", stats: [{n:"320g",l:"Day pack"},{n:"Lifetime",l:"Gear"},{n:"Lifetime",l:"Lifetime"}] },
  { name: "Inkroom Books", tagline: "A bookstore that still feels like one", category: "Retail", type: "Bookstore", desc: "Independent bookstore with staff picks, author nights, and a café corner that encourages lingering.", features: ["Staff picks", "Author events", "Kids corner", "Café"], cta: "Visit the shop", stats: [{n:"12k",l:"Titles"},{n:"Weekly",l:"Events"},{n:"Open",l:"Late Fri"}] },
  { name: "Pixel & Frame", tagline: "Cameras for people who see", category: "Retail", type: "Camera Store", desc: "Camera boutique for film and digital shooters—gear, workshops, and a rental desk.", features: ["Film + digital", "Rentals", "Workshops", "Trade-in"], cta: "Explore gear", stats: [{n:"Same day",l:"Rentals"},{n:"Lab",l:"On site"},{n:"Pro",l:"Desk"}] },
  { name: "Bloom Cart", tagline: "Flowers with a point of view", category: "Retail", type: "Florist", desc: "Seasonal floral studio for subscriptions, weddings, and arrangements that feel unfussy.", features: ["Weekly subs", "Weddings", "Same-day city", "Workshops"], cta: "Send flowers", stats: [{n:"Same day",l:"City delivery"},{n:"Seasonal",l:"Only"},{n:"Zero",l:"Foam"}] },
  { name: "Copper & Oak", tagline: "Furniture made to stay", category: "Retail", type: "Furniture", desc: "Solid-wood furniture studio offering custom dining tables, storage, and finish samples by mail.", features: ["Custom builds", "Sample kits", "White glove", "Lifetime program"], cta: "Design a piece", stats: [{n:"Solid",l:"Hardwood"},{n:"Lifetime",l:"Finish"},{n:"10yr",l:"Warranty"}] },
  { name: "Vista Optics", tagline: "Lenses that disappear on your face", category: "Retail", type: "Eyewear", desc: "Eyewear brand with virtual try-on, blue-light options, and frames built for all-day comfort.", features: ["Virtual try-on", "Prescription easy", "Blue light", "Home try 5"], cta: "Try frames", stats: [{n:"5",l:"Home try-on"},{n:"Free",l:"Returns"},{n:"UV400",l:"Standard"}] },

  // Creative (41-48)
  { name: "Forma Brand", tagline: "Identity systems that scale", category: "Creative Studio", type: "Branding Agency", desc: "Brand studio crafting identities, systems, and launch kits for companies leaving generic behind.", features: ["Identity systems", "Guidelines", "Launch kits", "Motion logos"], cta: "Start a brand", stats: [{n:"90+",l:"Brands"},{n:"8 wk",l:"Typical"},{n:"Global",l:"Clients"}] },
  { name: "Kinetic Film", tagline: "Stories in motion", category: "Creative Studio", type: "Video Production", desc: "Film production house for brand films, product launches, and documentary shorts.", features: ["Brand films", "Product spots", "Docs", "Color suite"], cta: "Watch reels", stats: [{n:"200+",l:"Films"},{n:"4K",l:"Pipeline"},{n:"On set",l:"Worldwide"}] },
  { name: "Typefoundry 9", tagline: "Type with character", category: "Creative Studio", type: "Type Foundry", desc: "Independent type foundry releasing retail and custom fonts for brands that care about letters.", features: ["Retail fonts", "Custom type", "Variable fonts", "Licensing clear"], cta: "Browse fonts", stats: [{n:"40+",l:"Families"},{n:"Variable",l:"Ready"},{n:"Desktop",l:"+ Web"}] },
  { name: "Studio North", tagline: "Interiors with quiet confidence", category: "Creative Studio", type: "Interior Design", desc: "Interior design studio for hospitality and residential projects with material-led storytelling.", features: ["Hospitality", "Residential", "FF&E", "Site supervision"], cta: "Tour projects", stats: [{n:"50+",l:"Spaces"},{n:"Full",l:"Service"},{n:"Material",l:"Library"}] },
  { name: "Amplitude Sound", tagline: "Audio brands remember", category: "Creative Studio", type: "Sound Design", desc: "Sonic branding and sound design for products, films, and spatial experiences.", features: ["Sonic logos", "UI sound", "Spatial audio", "Music beds"], cta: "Listen in", stats: [{n:"100+",l:"Brands"},{n:"Dolby",l:"Capable"},{n:"Remote",l:"Sessions"}] },
  { name: "Paperfold Studio", tagline: "Print that still matters", category: "Creative Studio", type: "Print Design", desc: "Editorial and packaging design studio for brands who still believe in paper as an experience.", features: ["Packaging", "Editorial", "Art direction", "Print manage"], cta: "See the work", stats: [{n:"Award",l:"Winning"},{n:"FSC",l:"Papers"},{n:"Global",l:"Print partners"}] },
  { name: "Lumen Stage", tagline: "Experiences you walk into", category: "Creative Studio", type: "Experiential", desc: "Experiential design for pop-ups, installations, and brand activations that feel intentional.", features: ["Pop-ups", "Installations", "Tech integrate", "Touring shows"], cta: "Plan an activation", stats: [{n:"1M+",l:"Visitors"},{n:"Multi",l:"City tours"},{n:"Full",l:"Build"}] },
  { name: "Frame Lab Photo", tagline: "Photography with a point of view", category: "Creative Studio", type: "Photography", desc: "Commercial photography studio for product, portrait, and campaign stills.", features: ["Product", "Portrait", "Campaigns", "Retouch house"], cta: "Book a shoot", stats: [{n:"Day rate",l:"Transparent"},{n:"Studio",l:"+ Location"},{n:"48h",l:"Selects"}] },

  // Home Services (49-55)
  { name: "Clearline Plumbing", tagline: "Honest plumbing, on time", category: "Home Services", type: "Plumbing", desc: "Licensed plumbers for repairs, remodels, and emergency calls with upfront pricing.", features: ["Upfront pricing", "24/7 emergency", "Remodel ready", "Water heaters"], cta: "Book a plumber", stats: [{n:"1hr",l:"Emergency ETA"},{n:"Licensed",l:"Insured"},{n:"5★",l:"Average"}] },
  { name: "Volt & Co", tagline: "Electrical work you can trust", category: "Home Services", type: "Electrician", desc: "Residential and light-commercial electricians for panels, EV chargers, and smart homes.", features: ["EV chargers", "Panel upgrades", "Smart home", "Inspections"], cta: "Get a quote", stats: [{n:"Same week",l:"Installs"},{n:"Code",l:"Perfect"},{n:"Warranty",l:"2 years"}] },
  { name: "Canopy Landscape", tagline: "Outdoor spaces that grow with you", category: "Home Services", type: "Landscaping", desc: "Landscape design and maintenance for native plantings, patios, and low-water gardens.", features: ["Native plants", "Hardscape", "Irrigation", "Seasonal care"], cta: "Design your yard", stats: [{n:"Native",l:"First"},{n:"Low water",l:"Plans"},{n:"Monthly",l:"Care"}] },
  { name: "Summit Roofing", tagline: "Roofs that last the storm", category: "Home Services", type: "Roofing", desc: "Roofing contractor for full replacements, repairs, and storm inspections with drone reports.", features: ["Drone inspect", "Full replace", "Storm claims", "Metal + shingle"], cta: "Free inspection", stats: [{n:"25yr",l:"Materials"},{n:"Drone",l:"Reports"},{n:"Insured",l:"Fully"}] },
  { name: "Nest Clean", tagline: "Cleaning that respects your home", category: "Home Services", type: "Cleaning Service", desc: "Eco-friendly home cleaning with vetted teams, flexible schedules, and supply options.", features: ["Eco products", "Vetted teams", "Flexible plans", "Move-out specials"], cta: "Book cleaning", stats: [{n:"Background",l:"Checked"},{n:"Recurring",l:"Discounts"},{n:"Insured",l:"Teams"}] },
  { name: "Forge HVAC", tagline: "Comfort engineered", category: "Home Services", type: "HVAC", desc: "Heating and cooling specialists for installs, tune-ups, and indoor air quality.", features: ["Installs", "Tune-ups", "Air quality", "Smart thermostats"], cta: "Schedule service", stats: [{n:"Same day",l:"Diagnose"},{n:"Energy",l:"Rebates help"},{n:"NATE",l:"Techs"}] },
  { name: "Anchor Moving", tagline: "Moves without the meltdown", category: "Home Services", type: "Moving Company", desc: "Local and long-distance movers with careful packing, transparent quotes, and storage options.", features: ["Local + long", "Packing", "Storage", "Corporate moves"], cta: "Get a move quote", stats: [{n:"0",l:"Hidden fees"},{n:"GPS",l:"Trucks"},{n:"White glove",l:"Option"}] },

  // Education (56-62)
  { name: "Lumen Academy", tagline: "Learning that sticks", category: "Education", type: "Online School", desc: "Online academy for adult learners—project-based courses in design, data, and leadership.", features: ["Project-based", "Mentor hours", "Cohorts", "Career projects"], cta: "Browse courses", stats: [{n:"40+",l:"Courses"},{n:"12wk",l:"Cohorts"},{n:"Job",l:"Outcomes"}] },
  { name: "Little Orbit", tagline: "Preschool for curious kids", category: "Education", type: "Preschool", desc: "Play-based preschool with outdoor classrooms, small ratios, and family workshops.", features: ["Outdoor class", "Small ratios", "Meals included", "Family nights"], cta: "Tour campus", stats: [{n:"1:6",l:"Ratio"},{n:"Nature",l:"First"},{n:"Ages 2–5",l:"Welcome"}] },
  { name: "Codebridge", tagline: "Kids who build, not just click", category: "Education", type: "Coding for Kids", desc: "After-school coding and robotics labs for ages 8–16 with portfolio showcases.", features: ["Robotics", "Web projects", "Showcases", "Camps"], cta: "Enroll a builder", stats: [{n:"Ages 8–16",l:"Focus"},{n:"Portfolio",l:"Driven"},{n:"Small",l:"Labs"}] },
  { name: "Fluent Path", tagline: "Languages for real conversations", category: "Education", type: "Language School", desc: "Immersive language school with conversation-first classes and cultural labs.", features: ["Conversation first", "Cultural labs", "Online + in person", "Business tracks"], cta: "Start speaking", stats: [{n:"12",l:"Languages"},{n:"Native",l:"Teachers"},{n:"CEFR",l:"Aligned"}] },
  { name: "Summit Tutors", tagline: "One-to-one that actually moves grades", category: "Education", type: "Tutoring", desc: "Vetted tutors for K–12 and test prep with progress dashboards for parents.", features: ["K–12 + tests", "Progress dash", "Vetted tutors", "Flexible hours"], cta: "Match a tutor", stats: [{n:"+1.2",l:"GPA avg lift"},{n:"SAT/ACT",l:"Prep"},{n:"48h",l:"Match"}] },
  { name: "Craft Atelier", tagline: "Hands-on skills, lifelong", category: "Education", type: "Maker School", desc: "Evening workshops in woodworking, ceramics, and metal for adults who want real craft.", features: ["Wood + ceramic", "Tool access", "Weekend intensives", "Open studio"], cta: "Join a workshop", stats: [{n:"Pro",l:"Instructors"},{n:"Tools",l:"Included"},{n:"All levels",l:"Welcome"}] },
  { name: "Beacon MBA Prep", tagline: "Admissions with clarity", category: "Education", type: "Test Prep / Admissions", desc: "MBA and grad admissions coaching with essay labs, interview drills, and school strategy.", features: ["Essay labs", "Interviews", "School strategy", "Scholarships"], cta: "Book strategy call", stats: [{n:"90%+",l:"Accept rate*"},{n:"M7",l:"Experience"},{n:"1:1",l:"Coaching"}] },

  // Travel (63-68)
  { name: "Wanderline", tagline: "Trips designed like products", category: "Travel & Hospitality", type: "Travel Agency", desc: "Boutique travel design for curious travelers—itineraries with local hosts and zero generic tours.", features: ["Local hosts", "Custom itineraries", "24/7 support", "Slow travel"], cta: "Plan a trip", stats: [{n:"40+",l:"Countries"},{n:"Bespoke",l:"Only"},{n:"4.9",l:"Traveler score"}] },
  { name: "Harbor House Inn", tagline: "Sleep by the water", category: "Travel & Hospitality", type: "Boutique Hotel", desc: "Waterfront boutique inn with twelve rooms, a kitchen garden, and mornings that start slow.", features: ["12 rooms", "Garden kitchen", "Spa baths", "Kayak dock"], cta: "Check availability", stats: [{n:"12",l:"Rooms only"},{n:"Breakfast",l:"Included"},{n:"Pet",l:"Friendly"}] },
  { name: "Apex Expeditions", tagline: "Guided adventures, serious safety", category: "Travel & Hospitality", type: "Adventure Travel", desc: "Guided mountaineering, trekking, and polar expeditions with world-class safety culture.", features: ["Guided peaks", "Training days", "Gear lists", "Medical kits"], cta: "View expeditions", stats: [{n:"UIAGM",l:"Guides"},{n:"Zero",l:"Compromise safety"},{n:"7",l:"Continents"}] },
  { name: "City Nest Stays", tagline: "Homes that feel like neighborhoods", category: "Travel & Hospitality", type: "Vacation Rentals", desc: "Curated vacation homes with hotel-grade cleaning, local guides, and host standards that stick.", features: ["Hotel cleaning", "Local guides", "Work desks", "Self check-in"], cta: "Find a stay", stats: [{n:"200+",l:"Homes"},{n:"Superhost",l:"Standard"},{n:"City",l:"Centers"}] },
  { name: "Rail & Room", tagline: "Slow trains, great hotels", category: "Travel & Hospitality", type: "Rail Travel", desc: "Curated rail journeys across continents with hotel handoffs and luggage transfer handled.", features: ["Rail passes help", "Hotel chain", "Luggage hop", "Scenic routes"], cta: "Browse journeys", stats: [{n:"Scenic",l:"Routes"},{n:"Door-door",l:"Bags"},{n:"EU + JP",l:"Focus"}] },
  { name: "Glow Retreats", tagline: "Rest is the itinerary", category: "Travel & Hospitality", type: "Wellness Retreat", desc: "Small-group wellness retreats combining movement, silence, and chef-led meals in remote places.", features: ["Small groups", "Movement", "Chef meals", "Digital silence"], cta: "See retreats", stats: [{n:"Max 12",l:"Guests"},{n:"5–7 day",l:"Stays"},{n:"Remote",l:"Locations"}] },

  // Finance (69-74)
  { name: "Northshore Wealth", tagline: "Wealth advice without the theater", category: "Finance", type: "Wealth Management", desc: "Fee-only wealth advisors for families building multi-decade plans—investing, tax, and legacy.", features: ["Fee-only", "Tax aware", "Legacy plans", "Family meetings"], cta: "Schedule intro", stats: [{n:"Fiduciary",l:"Always"},{n:"$500k+",l:"Typical"},{n:"CFP",l:"Team"}] },
  { name: "Seedpath Capital", tagline: "Early capital for builders", category: "Finance", type: "Venture Fund", desc: "Pre-seed and seed fund investing in infrastructure, climate, and developer tools.", features: ["Pre-seed + seed", "Operator network", "Follow-on", "Open thesis"], cta: "Send a deck", stats: [{n:"$50M",l:"Fund"},{n:"40+",l:"Portfolio"},{n:"Hands-on",l:"Partner"}] },
  { name: "Clearwater Insurance", tagline: "Coverage you actually understand", category: "Finance", type: "Insurance Agency", desc: "Independent insurance agency for home, auto, life, and small business—quotes without the maze.", features: ["Multi-carrier", "Business policies", "Claims help", "Annual reviews"], cta: "Get a quote", stats: [{n:"20+",l:"Carriers"},{n:"Same day",l:"Quotes"},{n:"Local",l:"Agents"}] },
  { name: "Stride Lending", tagline: "Lending built for small business", category: "Finance", type: "Business Lending", desc: "Transparent business loans and lines of credit with clear terms and human underwriters.", features: ["Lines of credit", "Term loans", "Human underwrite", "Fast funding"], cta: "Check eligibility", stats: [{n:"48h",l:"Decision"},{n:"No",l:"Surprise fees"},{n:"SMB",l:"Focused"}] },
  { name: "Mintledger", tagline: "Bookkeeping for founders who ship", category: "Finance", type: "Bookkeeping SaaS", desc: "Automated bookkeeping that categorizes transactions and hands you a clean close every month.", features: ["Auto categorize", "Monthly close", "Tax export", "Advisor chat"], cta: "Connect accounts", stats: [{n:"5 min",l:"Setup"},{n:"Bank-level",l:"Security"},{n:"CPA",l:"Reviewed"}] },
  { name: "Harbor Credit Union", tagline: "Banking that belongs to members", category: "Finance", type: "Credit Union", desc: "Community credit union with free checking, competitive mortgages, and real branch humans.", features: ["Free checking", "Mortgages", "Member rates", "Local branches"], cta: "Become a member", stats: [{n:"Member",l:"Owned"},{n:"NCUA",l:"Insured"},{n:"5★",l:"Support"}] },

  // Real Estate (75-79)
  { name: "Parcel & Key", tagline: "Homes found with intention", category: "Real Estate", type: "Residential Brokerage", desc: "Residential brokerage pairing data-rich search with agents who actually know the blocks.", features: ["Neighborhood intel", "Virtual tours", "Offer strategy", "Staging partners"], cta: "Start a search", stats: [{n:"$2B+",l:"Sold"},{n:"Local",l:"Experts"},{n:"Buyer + seller",l:"Both"}] },
  { name: "Grid Commercial", tagline: "Workplace real estate, simplified", category: "Real Estate", type: "Commercial RE", desc: "Commercial brokerage for offices, retail, and industrial—leases that match how teams work now.", features: ["Office + retail", "Lease advisory", "Site selection", "Portfolio ops"], cta: "Talk space", stats: [{n:"15M",l:"Sq ft advised"},{n:"National",l:"Coverage"},{n:"Tenant",l:"Rep focus"}] },
  { name: "Foundation Homes", tagline: "Custom builds without chaos", category: "Real Estate", type: "Home Builder", desc: "Custom home builder with fixed-price packages, transparent schedules, and design studio included.", features: ["Fixed packages", "Design studio", "Green options", "Warranty"], cta: "Tour models", stats: [{n:"On-time",l:"Guarantee"},{n:"Energy",l:"Star"},{n:"10yr",l:"Structure"}] },
  { name: "Loftify", tagline: "Property management that stays quiet", category: "Real Estate", type: "Property Management", desc: "Full-service property management for multifamily and single-family—tenants, maintenance, reporting.", features: ["Tenant portal", "24/7 maint", "Owner reports", "Leasing"], cta: "Manage with us", stats: [{n:"2k+",l:"Units"},{n:"98%",l:"Occupancy"},{n:"App",l:"Native"}] },
  { name: "Vista Land", tagline: "Land deals with due diligence", category: "Real Estate", type: "Land Brokerage", desc: "Specialized land brokerage for ranches, timber, and development sites with GIS-backed diligence.", features: ["GIS diligence", "Ranch + timber", "Dev sites", "Water rights"], cta: "Explore parcels", stats: [{n:"GIS",l:"First"},{n:"Rural",l:"Experts"},{n:"Nationwide",l:"Network"}] },

  // Automotive (80-83)
  { name: "Apex Motors", tagline: "Cars sold without the games", category: "Automotive", type: "Car Dealership", desc: "No-haggle dealership for new and certified pre-owned vehicles with transparent pricing online.", features: ["No haggle", "CPO program", "Trade-in online", "Home delivery"], cta: "Shop inventory", stats: [{n:"Online",l:"Price = lot"},{n:"CPO",l:"Inspected"},{n:"Home",l:"Delivery"}] },
  { name: "Torque Garage", tagline: "Service that tells you the truth", category: "Automotive", type: "Auto Repair", desc: "Independent auto shop with photo estimates, loaner bikes, and technicians who explain the work.", features: ["Photo estimates", "Loaner bikes", "EV service", "Fleet accounts"], cta: "Book service", stats: [{n:"ASE",l:"Master"},{n:"Same day",l:"Many jobs"},{n:"Fair",l:"Parts markup"}] },
  { name: "VoltFleet", tagline: "EV fleets that just work", category: "Automotive", type: "EV Fleet", desc: "Electric fleet solutions—vehicles, charging, and telematics for companies going electric.", features: ["Fleet EVs", "Charging plans", "Telematics", "TCO models"], cta: "Electrify fleet", stats: [{n:"TCO",l:"Models free"},{n:"Charge",l:"Partners"},{n:"National",l:"Support"}] },
  { name: "Detail Lab", tagline: "Detailing as craft", category: "Automotive", type: "Auto Detailing", desc: "Studio detailing for paint correction, ceramic coatings, and interior restoration.", features: ["Paint correction", "Ceramic coat", "Interior restore", "PPF"], cta: "Book detail", stats: [{n:"Studio",l:"Only"},{n:"5yr",l:"Coat warranty"},{n:"Concours",l:"Level"}] },

  // Beauty & Fitness (84-90)
  { name: "Aura Studio", tagline: "Hair that feels like you", category: "Beauty & Spa", type: "Hair Salon", desc: "Editorial hair salon for cuts, color, and extensions with consultation-first booking.", features: ["Cut + color", "Extensions", "Consults", "Bridal"], cta: "Book a chair", stats: [{n:"Senior",l:"Stylists"},{n:"Patch",l:"Tests free"},{n:"Late",l:"Thursdays"}] },
  { name: "Silk Spa", tagline: "Recovery you can feel", category: "Beauty & Spa", type: "Day Spa", desc: "Day spa focused on recovery—massage, facial protocols, and quiet rooms free of upsell pressure.", features: ["Massage", "Facials", "Quiet rooms", "Memberships"], cta: "Reserve spa time", stats: [{n:"90min",l:"Signature"},{n:"Organic",l:"Lines"},{n:"No",l:"Hard sell"}] },
  { name: "Ink & Needle", tagline: "Tattoos with permanence in mind", category: "Beauty & Spa", type: "Tattoo Studio", desc: "Custom tattoo studio for fine line, blackwork, and illustrative work by resident artists.", features: ["Custom only", "Fine line", "Blackwork", "Aftercare kit"], cta: "Request design", stats: [{n:"Custom",l:"Only"},{n:"Healed",l:"Photos"},{n:"Sterile",l:"Protocol"}] },
  { name: "Ironclad Gym", tagline: "Strength without the ego", category: "Fitness", type: "Gym", desc: "Strength gym with coaching, open floors, and programming for every experience level.", features: ["Coached lifts", "Open floor", "Programming", "Recovery zone"], cta: "Try a week free", stats: [{n:"24/7",l:"Access"},{n:"Coach",l:"On floor"},{n:"No",l:"Contracts"}] },
  { name: "Flow Reformer", tagline: "Pilates that rebuilds you", category: "Fitness", type: "Pilates Studio", desc: "Reformer Pilates studio with small classes, physical-therapy informed cues, and prenatal tracks.", features: ["Reformer", "Small class", "Prenatal", "Private sessions"], cta: "Book intro class", stats: [{n:"Max 8",l:"Per class"},{n:"PT-informed",l:"Cues"},{n:"New client",l:"Intro rate"}] },
  { name: "Stride Run Club", tagline: "Community miles", category: "Fitness", type: "Running Club", desc: "Community running club with coached plans, group runs, and race support for all paces.", features: ["Group runs", "Coached plans", "Race support", "All paces"], cta: "Join a run", stats: [{n:"Free",l:"Weekly runs"},{n:"All paces",l:"Welcome"},{n:"City",l:"Routes"}] },
  { name: "Peak Climb", tagline: "Climb higher, safely", category: "Fitness", type: "Climbing Gym", desc: "Indoor climbing gym with bouldering, top-rope, and youth programs in a bright warehouse space.", features: ["Boulder + rope", "Youth teams", "Gear rental", "Belay classes"], cta: "Day pass", stats: [{n:"15k",l:"Sq ft"},{n:"New sets",l:"Weekly"},{n:"Café",l:"On site"}] },

  // Legal, Nonprofit, Entertainment, Construction, Agriculture, Logistics (91-100)
  { name: "Harbor Law", tagline: "Counsel that speaks plain", category: "Legal", type: "Law Firm", desc: "Business and employment law firm for startups and SMBs—contracts, disputes, and compliance.", features: ["Business law", "Employment", "Contracts", "Flat fees where possible"], cta: "Book consult", stats: [{n:"Flat fee",l:"Menus"},{n:"Startup",l:"Focused"},{n:"48h",l:"Turnaround"}] },
  { name: "Civic Seed", tagline: "Funding the work that matters", category: "Nonprofit", type: "Nonprofit Org", desc: "Community nonprofit funding youth education, green spaces, and neighborhood resilience programs.", features: ["Youth programs", "Green spaces", "Volunteer hub", "Transparent impact"], cta: "Donate or volunteer", stats: [{n:"12k",l:"Youth served"},{n:"92¢",l:"To programs"},{n:"Open",l:"Books"}] },
  { name: "Velvet Room", tagline: "Live music, intimate nights", category: "Entertainment", type: "Music Venue", desc: "Intimate live music venue with standing room, vinyl bar, and a calendar that prioritizes artists.", features: ["Live calendar", "Vinyl bar", "Artist-first", "Private hires"], cta: "See shows", stats: [{n:"300",l:"Capacity"},{n:"All ages",l:"Some nights"},{n:"Standing",l:"Room"}] },
  { name: "Framehouse Cinema", tagline: "Cinema as it should be", category: "Entertainment", type: "Independent Cinema", desc: "Independent cinema screening repertory, new releases, and director Q&As with real butter popcorn.", features: ["Repertory", "New releases", "Q&As", "Membership"], cta: "Buy tickets", stats: [{n:"3",l:"Screens"},{n:"Member",l:"Perks"},{n:"35mm",l:"Capable"}] },
  { name: "Ironline Build", tagline: "Construction you can schedule against", category: "Construction", type: "General Contractor", desc: "General contractor for commercial TI and multifamily—schedules that hold and punch lists that close.", features: ["Commercial TI", "Multifamily", "Self-perform", "Safety first"], cta: "Request bid", stats: [{n:"On schedule",l:"Culture"},{n:"EMR 0.7",l:"Safety"},{n:"Bonded",l:"Insured"}] },
  { name: "Greenacre Farms", tagline: "Food grown with transparency", category: "Agriculture", type: "Organic Farm", desc: "Certified organic farm offering CSA shares, farm stands, and educational field days.", features: ["CSA shares", "Farm stand", "Field days", "Restaurant supply"], cta: "Join the CSA", stats: [{n:"Organic",l:"Certified"},{n:"120",l:"Acres"},{n:"Seasonal",l:"Boxes"}] },
  { name: "Swiftline Logistics", tagline: "Freight that arrives as promised", category: "Logistics", type: "Freight Broker", desc: "Freight brokerage with real-time tracking, dedicated lanes, and a ops team that picks up the phone.", features: ["Real-time track", "Dedicated lanes", "Warehousing", "Last mile"], cta: "Ship with us", stats: [{n:"99.2%",l:"On-time"},{n:"24/7",l:"Ops desk"},{n:"North America",l:"Coverage"}] },
  { name: "Beacon Vet", tagline: "Care for every life stage", category: "Health & Wellness", type: "Veterinary Clinic", desc: "Full-service veterinary clinic with wellness plans, surgery, and emergency hours for pets.", features: ["Wellness plans", "Surgery", "Emergency hours", "Dental"], cta: "Book pet visit", stats: [{n:"Fear-free",l:"Certified"},{n:"Same day",l:"Sick slots"},{n:"Open",l:"Sundays"}] },
  { name: "Nimbus Events", tagline: "Events that feel effortless", category: "Entertainment", type: "Event Planning", desc: "Full-service event planning for corporate offsites, weddings, and product launches.", features: ["Corporate", "Weddings", "Launches", "Vendor network"], cta: "Plan an event", stats: [{n:"500+",l:"Events"},{n:"Full",l:"Production"},{n:"Global",l:"Cities"}] },
  { name: "Oak & Stone Masonry", tagline: "Masonry that lasts generations", category: "Construction", type: "Masonry", desc: "Artisan masonry for fireplaces, facades, and restoration—stone, brick, and lime work.", features: ["Facades", "Fireplaces", "Restoration", "Lime work"], cta: "Request site visit", stats: [{n:"Master",l:"Masons"},{n:"Historic",l:"Capable"},{n:"Written",l:"Warranty"}] },
];

if (businesses.length !== 100) {
  console.error("Expected 100 businesses, got", businesses.length);
  process.exit(1);
}

const out = businesses.map((b, i) => {
  const id = i + 1;
  const palette = palettes[i % palettes.length];
  const layout = layouts[i % layouts.length];
  const scene = scenes[i % scenes.length];
  const slug = b.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  return {
    id,
    slug,
    ...b,
    palette,
    layout,
    scene,
    // slight per-page variation hooks
    heroStyle: i % 3,
    featureStyle: i % 4,
    testimonial: {
      quote: `Working with ${b.name} changed how we think about ${b.type.toLowerCase()}. The experience is polished and the results speak for themselves.`,
      author: ["Alex Rivera", "Jordan Lee", "Sam Okonkwo", "Morgan Chen", "Riley Patel"][i % 5],
      role: ["Founder", "Ops Lead", "Creative Director", "Homeowner", "Head of Product"][i % 5],
    },
  };
});

const file = `/** Auto-generated catalog of 100 landing page definitions */
window.LANDING_PAGES = ${JSON.stringify(out, null, 2)};
window.LANDING_CATEGORIES = ${JSON.stringify(categories, null, 2)};
window.LANDING_LAYOUTS = ${JSON.stringify(layouts, null, 2)};
`;

writeFileSync("/workspace/js/businesses.js", file);
console.log("Wrote", out.length, "businesses");
